# Constants
NUM_CAMERAS: 3
CAMERA_ID: [0,2,4]
IMAGE_WIDTH: 640
IMAGE_HEIGHT: 480
DARTBOARD_DIAMETER_MM: 451
DOUBLE_RING_OUTER_RADIUS_MM: 170

# Dartboard radii in mm
BULLSEYE_RADIUS_MM: 6.35
OUTER_BULL_RADIUS_MM: 15.9
TRIPLE_RING_INNER_RADIUS_MM: 99
TRIPLE_RING_OUTER_RADIUS_MM: 107
DOUBLE_RING_INNER_RADIUS_MM: 162
DOUBLE_RING_OUTER_RADIUS_MM: 170

# Dart tip radius in mm
TIP_RADIUS_MM: 1.15

# Kalman filter parameters
DT: 0.03333333333333333  # Assuming 30 FPS ---> 1.0 / 30.0
U_X: 0
U_Y: 0
STD_ACC: 1.0
X_STD_MEAS: 0.1
Y_STD_MEAS: 0.1

# Takeout parameters
TAKEOUT_THRESHOLD: 18000
TAKEOUT_DELAY: 3.0
