BULLSEYE_RADIUS_MM: 6.35
BULLSEYE_RADIUS_PX: 6
CAMERA_ID:
- 0
- 2
- 4
DARTBOARD_DIAMETER_MM: 451
DOUBLE_RING_INNER_RADIUS_MM: 162
DOUBLE_RING_INNER_RADIUS_PX: 172
DOUBLE_RING_OUTER_RADIUS_MM: 170
DOUBLE_RING_OUTER_RADIUS_PX: 180
DT: 0.03333333333333333
IMAGE_HEIGHT: 480
IMAGE_WIDTH: 640
NUM_CAMERAS: 3
OUTER_BULL_RADIUS_MM: 15.9
OUTER_BULL_RADIUS_PX: 16
PIXELS_PER_MM: 1.06430155210643
STD_ACC: 1.0
TAKEOUT_DELAY: 3.9
TAKEOUT_THRESHOLD: 18000
TIP_RADIUS_MM: 1.15
TRIPLE_RING_INNER_RADIUS_MM: 99
TRIPLE_RING_INNER_RADIUS_PX: 105
TRIPLE_RING_OUTER_RADIUS_MM: 107
TRIPLE_RING_OUTER_RADIUS_PX: 113
U_X: 0
U_Y: 0
X_STD_MEAS: 0.1
Y_STD_MEAS: 0.1
center: !!python/tuple
- 320
- 240
